Aplicacion/config/routes.rb
Rails.application.routes.draw do

  resources :productos
  resources :marcas
  root 'marcas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Aplicacion/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Aplicacion/app/models/marca.rb
class Marca < ApplicationRecord
	has_many :productos
	validates :nombre, :presence => {:message =>"es necesario para poder guardar"}
	#validates :nombre, presence: true, allow_blank: false
end

Aplicacion/app/models/producto.rb
class Producto < ApplicationRecord
	belongs_to :marca	
	validates :nombre, :presence => {:message =>"es necesario para poder guardar"}
	validates :marca, :presence => {:message =>"es necesaria para poder guardar"}
#
#validates_inclusion_of :precio, :in => 1..100
validates :precio, :inclusion => { :in => 1..100, :message => "debe ser entre 1 y 100 para poder guardar" }
#validates_format_of :precio, :with => /\A\d+(?:\.\d{0,2})?\z/
end

Aplicacion/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Aplicacion/app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :set_marca, only: [:show, :edit, :update, :destroy]

  # GET /marcas
  # GET /marcas.json
  def index
    @marcas = Marca.all
  end

  # GET /marcas/1
  # GET /marcas/1.json
  def show
  end

  # GET /marcas/new
  def new
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
  end

  # POST /marcas
  # POST /marcas.json
  def create
    @marca = Marca.new(marca_params)
    respond_to do |format|

      if @marca.save
        format.html { redirect_to @marca, notice: 'Marca creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marcas/1
  # PATCH/PUT /marcas/1.json
  def update
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to @marca, notice: 'Marca editada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    @marca.destroy
    respond_to do |format|
      format.html { redirect_to marcas_url, notice: 'Marca eliminada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marca_params
      params.require(:marca).permit(:nombre)
    end
end

Aplicacion/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
    @suma_precios = 0;
    @productos.each do  |producto|  
      @suma_precios = (@suma_precios + producto.precio).round(2)
  end
end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto editado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:marca_id,:nombre, :precio, :descripcion)
    end
end

Aplicacion/app/helpers/application_helper.rb
module ApplicationHelper
end

Aplicacion/app/helpers/marcas_helper.rb
module MarcasHelper
end

Aplicacion/app/helpers/productos_helper.rb
module ProductosHelper
end

Aplicacion/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aplicacion</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css" media="screen">
    body{
    	background-color: #ecf0f5;
    }
    .navbar-default {
    background-color: #3b9881;
    border-color: #3b9881;
	}.navbar-default .navbar-nav > li > a {
    color: #fff;
	}
	.navbar-default .navbar-brand {
    color: #fff;
		}
	.navbar-default .navbar-nav > li > a:hover, .navbar-default .navbar-nav > li > a:focus {
    color: #ecf0f5;
    background-color: transparent;
	}
	.navbar-default .navbar-brand:hover, .navbar-default .navbar-brand:focus {
    color: #ecf0f5;
    background-color: transparent;
	}
  .div-ver{
    background-color:white;
    font-size: 20px; 
  }
	table{
		background-color: #fff;

   		text-align: center;   
	}
    </style>
  </head>

  <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">HOME</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/marcas">Marcas</a></li>
      <li><a href="/productos">Productos</a></li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

Aplicacion/app/views/marcas/_form.html.erb
<div class="container">
<%= form_for(marca) do |f| %>
  <% if marca.errors.any? %>
   <center> <div id="error_explanation">
      <h2> Error:</h2>

      <ul style="list-style: none;">
      <% marca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    </center>
  <% end %>
<div class="form-horizontal">
 <div class="form-group">
    <%= f.label :nombre,:class => 'control-label col-sm-2' %>
     <div class="col-sm-8">
    <%= f.text_field :nombre,:class => 'form-control'  %>
    </div>
  </div>
 <div class="col-sm-offset-2 col-sm-10">
  <div class="actions">
    <%= f.submit "Guardar Marca",:class => 'btn btn-primary'%>
  </div>
  </div>
  </div>
<% end %>
</div>

Aplicacion/app/views/marcas/edit.html.erb
<center><h1 style="margin: 40px;">Editar Marca</h1></center>

<%= render 'form', marca: @marca %>
<center>
<%= link_to 'Mostrar', @marca %> |
<%= link_to 'Regresar', marcas_path %>
</center>

Aplicacion/app/views/marcas/index.html.erb
<p id="notice"><%= notice %></p>

<center> <h1>Marcas</h1> </center>
<div class="container"> <table class="table table-striped">
  <thead>
    <tr>
      <th><center> Nombre </center> </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marcas.each do |marca| %>
      <tr>
        <td><%= marca.nombre %></td>
        <td><%= link_to 'Mostrar', marca %></td>
        <td><%= link_to 'Editar', edit_marca_path(marca) %></td>
        <td><%= link_to 'Eliminar', marca, method: :delete, data: { confirm: "¿Estás seguro de borrar la marca #{marca.nombre}?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<a href="/marcas/new" class="btn btn-primary" role="button" style="float: right;">Agregar Marca</a>
</div>

<br>

Aplicacion/app/views/marcas/new.html.erb
<center><h1 style="margin: 40px;">Crear Marca</h1></center>

<%= render 'form', marca: @marca %>
<center><%= link_to 'Regresar', marcas_path %>
</center>

Aplicacion/app/views/marcas/show.html.erb
<p id="notice"><%= notice %></p>

<center  class="container"> <h3>Marca Detalles</h3> 
<br/>
<div class="div-ver">
<p style="font-size: 20px">
  <strong>Nombre:</strong>
  <%= @marca.nombre %>
</p>

<%= link_to 'Editar', edit_marca_path(@marca) %> |
<%= link_to 'Regresar', marcas_path %>
</div>

</center>

Aplicacion/app/views/productos/_form.html.erb
<div class="container">
<%= simple_form_for(producto) do |f| %>
  <% if producto.errors.any? %>
  <center>
    <div id="error_explanation">
      <h2>Error</h2>

      <ul style="list-style: none;">
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </center>
  <% end %>
  <div class="form-horizontal">
<div class="form-group">
  <%= f.label "Marca",:class => 'control-label col-sm-2' %>
  <div class="col-sm-9">
  <%= f.collection_select :marca_id, Marca.all, :id, :nombre, {}, {class: "form-control"} %>
</div>
</div>

  <div class="form-group">
    <%= f.label "Nombre",:class => 'control-label col-sm-2' %>
     <div class="col-sm-9">
    <%= f.text_field :nombre,:class => 'form-control'  %>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :precio,:class => 'control-label col-sm-2'%>
     <div class="col-sm-4">
    <%= f.number_field :precio,:class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :descripcion,:class => 'control-label col-sm-2' %>
    <div class="col-sm-9">
    <%= f.text_area :descripcion,:class => 'form-control' %>
    </div>
  </div>

 <div class="col-sm-offset-2 col-sm-10">
  <div class="actions">
    <%= f.submit "Guardar Producto",:class => 'btn btn-primary'%>
  </div>
 </div>
  </div>
<% end %>
</div>

Aplicacion/app/views/productos/edit.html.erb
<center><h1 style="margin: 40px;">Editar Producto</h1></center>

<%= render 'form', producto: @producto %>
<center>
<%= link_to 'Mostrar', @producto %> |
<%= link_to 'Regresar', productos_path %>
</center>

Aplicacion/app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<center> <h1>Productos</h1> </center>
 <div class="container">  
 <table class="table table-striped">

  <thead>
    <tr>
      <th>Marca</th>
      <th>Nombre</th>
      <th>Precio</th>
      <th><center>Descripcion</center></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.marca.nombre %></td>
        <td><%= producto.nombre %></td>
        <td><%= (producto.precio).round(2) %></td>
        <td><%= producto.descripcion %></td>
        <td><%= link_to 'Mostrar', producto %></td>
        <td><%= link_to 'Editar', edit_producto_path(producto) %></td>
        <td><%= link_to 'Eliminar', producto, method: :delete, data:  { confirm: "¿Estás seguro de borrar el producto: #{producto.nombre}?" }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<a href="/productos/new" class="btn btn-primary" role="button" style="float: right;">Agregar Producto</a>
<div> 
<label>Valor de productos:</label>
<label style="font-size: 20px" ><%= @suma_precios %></label>
</div>
</div>

Aplicacion/app/views/productos/new.html.erb
<center><h1 style="margin: 40px;">Nuevo Producto</h1></center>

<%= render 'form', producto: @producto %>
<center><%= link_to 'Regresar', productos_path %>
</center>

Aplicacion/app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<center class="container"> <h3>Producto Detalles</h3> 
<br/>
<div class="div-ver">
<p>
   <strong>Marca:</strong>
  <%= @producto.marca.nombre %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @producto.descripcion %>
</p>

<%= link_to 'Editar', edit_producto_path(@producto) %> |
<%= link_to 'Regresar', productos_path %>
</div>

</center>